# Generated by Django 3.2.10 on 2021-12-24 14:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gift.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toy', '0024_auto_20211206_1853'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=gift.models.generate_code, max_length=255, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Gift code')),
                ('redeemed', models.PositiveIntegerField(default=0, verbose_name='Redeemed')),
                ('max_usages', models.PositiveIntegerField(default=1, verbose_name='Max usage')),
                ('allow_ignore_quota', models.BooleanField(default=False, help_text='If activated, a holder of this voucher code can buy tickets, even if there are none left.', verbose_name='Allow to bypass quota')),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_codes', to='toy.toypage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('code',),
                'unique_together': {('toy', 'code')},
            },
        ),
    ]
