# Generated by Django 3.2.10 on 2021-12-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='gifted',
            field=models.BooleanField(default=False),
        ),
    ]
