# Generated by Django 3.2.10 on 2021-12-28 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0002_gift_gifted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Company name')),
                ('start_datetime', models.DateTimeField(verbose_name='Event start date time')),
                ('end_datetime', models.DateTimeField(verbose_name='Event end date time')),
                ('number_of_codes', models.IntegerField(verbose_name='Number of codes')),
                ('description', models.TextField(blank=True, verbose_name='Comments')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='gift',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gift.event'),
        ),
    ]
